### PR TITLE
Small refactoring in JLoadTest

### PR DESCRIPTION
**Pull request by Pryanic**
Please merge it as soon as possible.

### CODE REVIEW

**Comment by dlatnikov** [comment]
to keep existing naming logics of in your case it is necessary to add new method(s):
addListener(s)

**Comment by Pryanic** [comment]
Ok now problems

**Comment by Pryanic** [comment]
@dlatnikov please look at it again

**Comment by Pryanic** [comment]
@dlatnikov @gd-jagger-jenkins-robot please look at it again

**Pull request merged**
